### ISSUE TITLE
Public Polls that show who voted for each option

### ISSUE THREAD

**Issue by apoapostolov** [Forien/foundryvtt-forien-easy-polls#1]
The anonymous poll is great for asking questions such as "did you like today's session?" or "did the BBEG deserve to die?" but when it comes to "who can come tomorrow for the next session?" you want to see what everyone posted. 

My proposal is that a new public poll type is added. In that poll type, you have the player names or character names under each bar in the poll. A visual way to do this would be to use a tiny player or character tokens as assigned to players. This would make it very similar to polls in Facebook Messenger.

**Comment by Forien** [comment]
Done in [v1.0.1](https://github.com/Forien/foundryvtt-forien-easy-polls/releases/tag/v1.0.1)

**Comment by apoapostolov** [comment]
Thank you very much!
