### ISSUE TITLE
Register the poll command for the Chat Commander module

### ISSUE THREAD

**Issue by elespike** [Forien/foundryvtt-forien-easy-polls#10]
Hello,

It would be nice to have the `/poll` command registered with the Chat Commander module for auto-completion in the chat, according to https://gitlab.com/woodentavern/foundryvtt-chat-command-lib#registering-or-removing-commands.

**Comment by Forien** [comment]
Added support in new version. Since I never used Chat Commander before, please let me know if everything works as intended or if there is something I could improve :)

**Comment by elespike** [comment]
Looks great, and works perfectly, thank you! :D
Only thing I can suggest is adding an icon, but that's just a tiny detail.

![image](https://github.com/Forien/foundryvtt-forien-easy-polls/assets/14970655/6bae864c-15d6-4c56-880e-37b687062569)
---
![image](https://github.com/Forien/foundryvtt-forien-easy-polls/assets/14970655/45f02fc6-5feb-4961-80c1-8b30a0dbf8f9)
