### ISSUE TITLE
Open a "Create Poll" Dialog with macro?

### ISSUE THREAD

**Issue by MastaGooz** [Forien/foundryvtt-forien-easy-polls#14]
Hi !
I love this module, thanks for doing it !

I was wondering if there is a way to open a "Create Poll" Dialog via a macro?

**Comment by Forien** [comment]
Hey, 

I'm happy that you find my module useful :)

And yes, there is a way via Forien's Easy Polls' API. Here is how you can do it:

```js
game.modules.get('forien-easy-polls').api.renderPollDialog();
```

Similarly, if you would like to be able to open Saved Polls Dialog, you can use:
```js
game.modules.get('forien-easy-polls').api.renderSavedPollsApp();
```

Let me know if there are any further issues :)

**Comment by MastaGooz** [comment]
Thanks man, this is awesome !
