### ISSUE TITLE
[BUG] Poll conflicts with 2 mods, not catching /p commands

### ISSUE THREAD

**Issue by weihanderz** [Forien/foundryvtt-forien-easy-polls#2]
**Module Version:** v0.1.2

**Describe the bug**
While the following 2 mods are active, Forien's easy polls is not able to catch /p commands

• Meme - Moerills Expandable Markdown Editor (https://github.com/Moerill/fvtt-markdown-editor)
Specifically while the chat markdown support is active
and
• The Furnace (https://github.com/kakaroto/fvtt-module-furnace)
are active.

**To Reproduce**
1. Enter a game with mods "The Furnace" and "Meme - Moerills Expandable Markdown Editor" are on with the latter setting of chat markdown support being active
2. Try to create a poll:
```
/p This is a poll
Yes
No
```
Text comes out as:
```
/p This is a pollYesNo
```

**Expected behavior**
Polls to catch /p command and create a poll

**Browser:**
 Chrome

**Foundry Version:** 
0.7.9
**Game System:** 
D&D 5e

**Comment by Forien** [comment]
There is also a `/poll` command.

And since [v1.0.1](https://github.com/Forien/foundryvtt-forien-easy-polls/releases/tag/v1.0.1) there is also a Dialog UI to make Polls
